# Generated by Django 5.1 on 2024-09-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('duration', models.FloatField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(default='nothing.jpg', upload_to='media/movies')),
            ],
        ),
    ]
